export const iconList = [
    "icon-arrow-down",
    "icon-arrow-left",
    "icon-arrow-right",
    "icon-arrow-up",
    "icon-backspace",
    "icon-bigger",
    "icon-book",
    "icon-box",
    "icon-check",
    "icon-chevron-down",
    "icon-chevron-left",
    "icon-chevron-right",
    "icon-chevron-up",
    "icon-cloud",
    "icon-comment",
    "icon-copy",
    "icon-cross",
    "icon-desktop",
    "icon-document",
    "icon-documents",
    "icon-edit",
    "icon-expand",
    "icon-export",
    "icon-floppy",
    "icon-github",
    "icon-graph",
    "icon-health",
    "icon-heart",
    "icon-help",
    "icon-home",
    "icon-icon",
    "icon-image",
    "icon-implode",
    "icon-import",
    "icon-info",
    "icon-integrations",
    "icon-invisible",
    "icon-lab",
    "icon-label",
    "icon-laptop",
    "icon-link",
    "icon-lock",
    "icon-locked",
    "icon-mobile",
    "icon-moon",
    "icon-more",
    "icon-printer",
    "icon-profile",
    "icon-reports",
    "icon-search",
    "icon-send",
    "icon-settings",
    "icon-share",
    "icon-slack",
    "icon-smaller",
    "icon-sun",
    "icon-team",
    "icon-time",
    "icon-visible",
    "icon-vsf",
    "icon-warning",
    "icon-warning2"
];

export const iconListType = [...iconList] as const;

export enum Icons {
    ICON_ARROW_DOWN = "icon-arrow-down",
    ICON_ARROW_LEFT = "icon-arrow-left",
    ICON_ARROW_RIGHT = "icon-arrow-right",
    ICON_ARROW_UP = "icon-arrow-up",
    ICON_BACKSPACE = "icon-backspace",
    ICON_BIGGER = "icon-bigger",
    ICON_BOOK = "icon-book",
    ICON_BOX = "icon-box",
    ICON_CHECK = "icon-check",
    ICON_CHEVRON_DOWN = "icon-chevron-down",
    ICON_CHEVRON_LEFT = "icon-chevron-left",
    ICON_CHEVRON_RIGHT = "icon-chevron-right",
    ICON_CHEVRON_UP = "icon-chevron-up",
    ICON_CLOUD = "icon-cloud",
    ICON_COMMENT = "icon-comment",
    ICON_COPY = "icon-copy",
    ICON_CROSS = "icon-cross",
    ICON_DESKTOP = "icon-desktop",
    ICON_DOCUMENT = "icon-document",
    ICON_DOCUMENTS = "icon-documents",
    ICON_EDIT = "icon-edit",
    ICON_EXPAND = "icon-expand",
    ICON_EXPORT = "icon-export",
    ICON_FLOPPY = "icon-floppy",
    ICON_GITHUB = "icon-github",
    ICON_GRAPH = "icon-graph",
    ICON_HEALTH = "icon-health",
    ICON_HEART = "icon-heart",
    ICON_HELP = "icon-help",
    ICON_HOME = "icon-home",
    ICON_ICON = "icon-icon",
    ICON_IMAGE = "icon-image",
    ICON_IMPLODE = "icon-implode",
    ICON_IMPORT = "icon-import",
    ICON_INFO = "icon-info",
    ICON_INTEGRATIONS = "icon-integrations",
    ICON_INVISIBLE = "icon-invisible",
    ICON_LAB = "icon-lab",
    ICON_LABEL = "icon-label",
    ICON_LAPTOP = "icon-laptop",
    ICON_LINK = "icon-link",
    ICON_LOCK = "icon-lock",
    ICON_LOCKED = "icon-locked",
    ICON_MOBILE = "icon-mobile",
    ICON_MOON = "icon-moon",
    ICON_MORE = "icon-more",
    ICON_PRINTER = "icon-printer",
    ICON_PROFILE = "icon-profile",
    ICON_REPORTS = "icon-reports",
    ICON_SEARCH = "icon-search",
    ICON_SEND = "icon-send",
    ICON_SETTINGS = "icon-settings",
    ICON_SHARE = "icon-share",
    ICON_SLACK = "icon-slack",
    ICON_SMALLER = "icon-smaller",
    ICON_SUN = "icon-sun",
    ICON_TEAM = "icon-team",
    ICON_TIME = "icon-time",
    ICON_VISIBLE = "icon-visible",
    ICON_VSF = "icon-vsf",
    ICON_WARNING = "icon-warning",
    ICON_WARNING2 = "icon-warning2"
}
