name: Test & Publish

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - name: Checkout
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@sil'

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm test --if-present

      - name: Version
        run: npm version patch

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}